<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Amazon_Back_End</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="images\**" />
    <Content Remove="images\**" />
    <EmbeddedResource Remove="images\**" />
    <None Remove="images\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" Version="3.7.413" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
  </ItemGroup>

	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\business_logic\business_logic.csproj" />
		<ProjectReference Include="..\data_access\data_access.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="uploading\" />
	</ItemGroup>


</Project>
